@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhYWFlODdkNmExZmRiYjkxMzg3NzIiLCJpYXQiOjE2NjY4ODY0MDgsImV4cCI6MTY2NzIzMjAwOH0.jjZd3uXrgRFBoYmhcoqMCLNq9ZpdJwrLatYiJbQiktc

### LOGIN
POST {{API_URL}}/login
Content-Type: application/json

{
  "email": "los@los.los",
  "password": "los123" 
}

### SIGNUP
POST {{API_URL}}/signup
Content-Type: application/json

{
  "email": "los@los.los",
  "password": "los123" 
}

### PROTECTED ROUTE (Reject without token)
GET {{API_URL}}/todos
Authorization: {{TOKEN}}